
services:
  db:
    image: mysql:9.6
    container_name: migration_container
    env_file: ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s 

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports: 
      - 8080:8080

  api:
    build: ./api.
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: ./api/.env
    environment:
      MYSQL_HOST: db  
    restart: unless-stopped

  frontend:
    image: node:20  
    depends_on:
      - api
    volumes: 
      - "./:/app" 
    working_dir: /app
    ports: 
      - "3000:3000" 
    command: sh -c "npm install && npm start"
    restart: "no"
    healthcheck:
      test: "curl -f http://localhost:3000/"
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s 


