
services:
  db:
    image: mysql:9.6
    container_name: migration_container
    env_file: mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sqlfiles/:/docker-entrypoint-initdb.d/
      # - mysql_data:/var/lib/mysql
    healthcheck:

      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ] 
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports: 
      - 8080:8080

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: api.env
    restart: unless-stopped
    environment:
      MYSQL_HOST: db  
    volumes:
      - ./api:/app 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/users || exit 1"]


  frontend:
    build: ./     
    ports: 
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_PORT=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    volumes: 
      - ./:/app  
      - /app/node_modules

#volumes:
#  mysql_data: