[registry_hosts]

#Liste des IP
35.180.100.149

[registry_hosts:vars]

# Variables communes a tous les hotes du groupe
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/registry-key-terraform.pem
# Déasactive la vérification de la clé hote pour éviter le prompt "yes/no"
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
