name: Build and Test React Application 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      #- name: Run tests
      #  run: |
      #    cd my-app
      #    npm i
      #    npm test -- --coverage

      - name: Build application
        run: |
          cd my-app
          npm i
          npm run build

  publish-npm:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Check version and publish
        run: |
          cd my-app
          npm i
          
          # Version locale vs NPM
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          echo "Local: $LOCAL_VERSION"
          
          NPM_VERSION=$(npm view chloe-leonard-ci-ynov version 2>/dev/null)
          echo "NPM: $NPM_VERSION"
          
          if [[ "$LOCAL_VERSION" > "$NPM_VERSION" ]]; then
            echo "Publishing new version $LOCAL_VERSION"
            git config --global user.email "chloeleo44@hotmail.com"
            git config --global user.name "chloe-leonard337"
            npm run build-npm-ci
            npm version patch
            npm publish
            git add .
            git commit -m "updated version"
            git push
          else
            echo "Version already published, skipping"
            exit 0
          fi
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: my-app
          build: npm run build
          start: npm run start

      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-app/build

  build-docker:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Build & Run MySQL
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
        run: |
          cd ./my-app/mysql

          echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > mysql.env
          echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> mysql.env
          
          docker build -t migration_mysql .
          docker run -d --env-file mysql.env -p 3306:3306 --name migration_container migration_mysql

          sleep 5
          echo "=== API LOGS ==="
          docker logs migration_container || echo "No logs"
          
          # Vérifie état
          echo "=== Docker PS ==="
          docker ps -a --filter name=migration_container

      - name: Wait for MySQL
        run: sleep 15 
        shell: bash 

      - name: Build & Run API
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          cd ./my-app/api

          echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > api.env
          echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> api.env
          echo "MYSQL_USER=$MYSQL_USER" >> api.env
          echo "MYSQL_HOST=$MYSQL_HOST" >> api.env
          
          docker build -t ynov-ci-cd-api .
          docker run -d --name ynov-api --env-file api.env -p 8000:8000 ynov-ci-cd-api
          
          sleep 5
          echo "=== API LOGS ==="
          docker logs ynov-api || echo "No logs"
          
          # Vérifie état
          echo "=== Docker PS ==="
          docker ps -a --filter name=ynov-api 
          

      - name: Check API /users status 200
        run: |
          sleep 15
          docker ps | grep ynov-api  || (echo "API not running!" && exit 1)
          
          for i in {1..10}; do
            if curl -s -o /tmp/response.json -w "%{http_code}" http://localhost:8000/users > /tmp/http_code; then
              HTTP_CODE=$(cat /tmp/http_code)
              break
            fi
            echo "Tentative $i/10..."
            sleep 3
          done
          
          echo "HTTP_CODE=$HTTP_CODE"
          cat /tmp/response.json
          
          if [ "$HTTP_CODE" != "200" ]; then
            echo "ERREUR HTTP $HTTP_CODE"
            exit 1
          fi
          
      - name: Check users exist
        run: curl -s http://localhost:8000/users | jq -e '.utilisateurs | length > 0' || exit 1




  deploy:
    needs: [build-and-test, publish-npm]  
    permissions: 
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
